// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0hb6Y1wHYwJdojLs4lO4duCxqXlWs25k',
    appId: '1:36375765225:web:924402ff910bfd3b48d078',
    messagingSenderId: '36375765225',
    projectId: 'com-example-chatting',
    authDomain: 'com-example-chatting.firebaseapp.com',
    storageBucket: 'com-example-chatting.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqZ-5Hgwpxafqb-CZ6WcKAzUKu65fPp-o',
    appId: '1:36375765225:android:54da4c82ea893bf748d078',
    messagingSenderId: '36375765225',
    projectId: 'com-example-chatting',
    storageBucket: 'com-example-chatting.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpylMOTOVWT_Sqykqeu6zcLf9JoSVPsmA',
    appId: '1:36375765225:ios:1a17707377a3201b48d078',
    messagingSenderId: '36375765225',
    projectId: 'com-example-chatting',
    storageBucket: 'com-example-chatting.firebasestorage.app',
    iosBundleId: 'com.example.chatting',
  );
}
